# Generated by Django 6.0 on 2026-04-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0003_question_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
