# Generated by Django 6.0 on 2026-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0004_alter_submission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
