# Generated by Django 6.0 on 2026-05-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0005_question_option_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='preamble',
            field=models.TextField(blank=True, help_text='Text to display before the question (e.g., case study, scenario)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
