# Generated by Django 6.0 on 2026-05-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0006_question_preamble_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('A', 'Section A - MCQ'), ('B', 'Section B - Theory')], default='A', max_length=1),
        ),
    ]
